config/routes.rb
Rgallery::Application.routes.draw do

  get "site/index"
  
  get 'admin' => 'admin#index'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create 
    get 'logout' => :destroy
  end

  resources :ishow
  
  resources :gshow
  
  resources :cshow 

  resources :users

  resources :categories

  resources :images

  resources :galleries

  get "dirlist/index"

  post "dirlist/index"

  post "gshow/:id" => "gshow#show"

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

root to: 'site#index', as: 'site'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :galleries
  validates :title, presence: true
  validates :title, uniqueness: true
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  validates :title, :description, presence: true
  validates :title, uniqueness: true
  has_many :images
  belongs_to :category
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :gallery  
  validates_uniqueness_of :fname, :scope => [:gallery_id]
end

app/models/message.rb
class Message
    include ActiveModel::Validations
    include ActiveModel::Conversion
    extend ActiveModel::Naming
    attr_accessor :name, :email, :subject, :body

    validates :name, :email, :subject, :body, :presence => true
    validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true    

    def initialize(attributes = {})
        attributes.each do |name, value|
            send("#{name}=", value)
        end
    end
                  
    def persisted?
        false
    end
                          
end    

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/cshow_controller.rb
class CshowController < ApplicationController
  layout "main"
  skip_before_filter :authorize
  def index
    respond_to do |format|
        format.html { redirect_to site_url }
    end
  end
  def show 
    @columns = 3
    @galleries = Gallery.where(:category_id => params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @galleries }
    end
  end
end

app/controllers/ishow_controller.rb
class IshowController < ApplicationController
  layout "main"
  skip_before_filter :authorize

#* _lt => less than
#* _gt => greater than
#* _lte => less than or equal to
#* _gte => greater than or equal to
#* _ne => not equal to
#* _not => not equal to

  def index
    respond_to do |format|
        format.html { redirect_to site_url }
    end
  end

  def show

    @path = "#{Rails.root}/public"
    tabimages = 14
    @ids = []
    @image = Image.find(params[:id])
    imagerange = Image.all(:conditions  => ['gallery_id = ? AND id < ? AND id > ?', @image.gallery_id,@image.id+tabimages ,@image.id-tabimages])
    imagerange.each do |img|
      @ids << img.id.to_i
    end
    arr_id = @ids.index(params[:id].to_i)

    @next_img_id = @ids[arr_id+1] if @ids[arr_id+1]
    @prev_img_id = @ids[arr_id-1] if @ids[arr_id-1] and arr_id != 0

    @startid = arr_id - tabimages/2
    @endid = arr_id + tabimages/2
    if @ids.length < tabimages 
      @startid = 0
      @endid = @ids.length - 1
    elsif arr_id < (tabimages - 1)
      @startid = 0
      @endid = (tabimages - 1)
    elsif arr_id > (@ids.length - tabimages)
      @startid = @ids.length - tabimages
      @endid = @ids.length - 1
    end

    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @images }
    end
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout "main"
  skip_before_filter :authorize
  def index
    @table_cells = Hash.new
    @cat_thumbs = Hash.new{|h,k| h[k]=Hash.new(&h.default_proc) }
    cthumb = ""
    @categories_number = Category.all.count
    @row_number = (((@categories_number/2).to_i)+1)
    
    Category.all.each do |ff|
      Gallery.where(:category_id => ff.id).each do |ss| 
        ct = Image.where(:gallery_id => ss.id, :gthumb => true).all(:limit => 1, :order => 'random()')
        ct.each do |cth|
          /(.*)\.jpg|png/i.match(cth.fname)
          iname = $1
          cthumb = "../#{cth.path}/category_thumb/#{iname}.png"
        end
      end
      while(1) do 
        key1 = rand(1..3)
        key2 = rand(1..@row_number)
        if @cat_thumbs[key1][key2] == {}
          @cat_thumbs[key1][key2] = "#{cthumb}:#{ff.id}"
          break
        end
      end

    end  

  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/cshow_helper.rb
module CshowHelper
end

app/helpers/dirlist_helper.rb
module DirlistHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/gshow_helper.rb
module GshowHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/ishow_helper.rb
module IshowHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ishow/show.html.erb
<div class="main">
  <div ><a href="<%= site_path %>"><img src="../home.png"></a></div>    
  <div id="image">
  <table id="image">
    <tr>
      <td>
        <% if @prev_img_id %>         
            <a href="/ishow/<%= @prev_img_id %>"><<</a>
        <% end %>
      </td>
      <td><img id="showimg" src="<%= "../#{@image.path}/originals/#{@image.fname}" %>" alt="<%= @image.fname %>" height="700"/></td>      
      <td>
        <% if @next_img_id %>
          <a href="/ishow/<%= @next_img_id %>">>></a>
        <% end %>
      </td>
    </tr>
  </table>
  </div>

  <div class="sc_menu">
    <ul class="sc_menu">
    <% @startid.upto(@endid) do |i| %>
      <% img = Image.find(@ids[i])%>
      <% img.id == @image.id ? cssid = "class='currentimg'" : cssid = ""%>
      <li><a <%= cssid %> href="/ishow/<%= img.id %>">
        <img src="<%="../#{img.path}/75x75/#{img.fname}"%>" alt="<%= img.fname %>"/> <!-- <span><%= img.fname %></span> -->
      </a></li>
    <% end %>
    </ul>
  </div>


</div>

<script>
$(function(){
    //Get our elements for faster access and set overlay width
    var div = $('div.sc_menu'),
                 ul = $('ul.sc_menu'),
                 // unordered list's left margin
                 ulPadding = 15;

    //Get menu width
    var divWidth = div.width();

    //Remove scrollbars
    div.css({overflow: 'hidden'});

    //Find last image container
    var lastLi = ul.find('li:last-child');

    //When user move mouse over menu
    div.mousemove(function(e){

      //As images are loaded ul width increases,
      //so we recalculate it each time
      var ulWidth = lastLi[0].offsetLeft + lastLi.outerWidth() + ulPadding;

      var left = (e.pageX - div.offset().left) * (ulWidth-divWidth) / divWidth;
      div.scrollLeft(left);
    });
});

</script>