config/routes.rb
Rgallery::Application.routes.draw do

  get "site/index"
  
  get 'admin' => 'admin#index'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create 
    get 'logout' => :destroy
  end

  resources :ishow
  
  resources :gshow
  
  resources :cshow 

  resources :users

  resources :categories

  resources :images

  resources :galleries

  get "dirlist/index"

  post "dirlist/index"

  post "gshow/:id" => "gshow#show"

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

root to: 'site#index', as: 'site'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :galleries
  validates :title, presence: true
  validates :title, uniqueness: true
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  validates :title, :description, presence: true
  validates :title, uniqueness: true
  has_many :images
  belongs_to :category
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :gallery  
  validates_uniqueness_of :fname, :scope => [:gallery_id]
end

app/models/message.rb
class Message
    include ActiveModel::Validations
    include ActiveModel::Conversion
    extend ActiveModel::Naming
    attr_accessor :name, :email, :subject, :body

    validates :name, :email, :subject, :body, :presence => true
    validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true    

    def initialize(attributes = {})
        attributes.each do |name, value|
            send("#{name}=", value)
        end
    end
                  
    def persisted?
        false
    end
                          
end    

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/cshow_controller.rb
class CshowController < ApplicationController
  layout "main"
  skip_before_filter :authorize
  def index
    respond_to do |format|
        format.html { redirect_to site_url }
    end
  end
  def show 
    @columns = 3
    @galleries = Gallery.where(:category_id => params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @galleries }
    end
  end
end

app/controllers/gshow_controller.rb
class GshowController < ApplicationController
  layout "main"
  skip_before_filter :authorize
  def index
    respond_to do |format|
        format.html { redirect_to site_url }
    end
  end
  def show
    @gallery = Gallery.find(params[:id])
    
    @sss = params[:perpage]
    @fff = params[:cols]
    @bbb = "prazno" if session[:cols].nil?
    session[:cols] = 3 if session[:cols].nil?
    session[:perpage] = 15 if ! session[:perpage]

    if params[:cols]
        session[:perpage] = (params[:cols].to_i)*5
        session[:cols] = params[:cols].to_i
    end
    if params[:perpage]
        session[:perpage] = params[:perpage].to_i
    end
    
    @images = Image.where(:gallery_id => params[:id ]).paginate page: params[:page], order: 'created_at asc', per_page: session[:perpage]
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @images }
    end

  end  
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  # GET /images
  # GET /images.json
  def index
#    Image.delete_all
#    Gallery.delete_all
    #@images = Image.all
    @perpage = 10
    @perpage = params[:perpage].to_i if params[:perpage]
    if params[:gal]
      @images = Image.where(:gallery_id => params[:gal]).paginate page: params[:page], order: 'created_at desc', per_page: @perpage
    else 
      @images = Image.paginate page: params[:page], order: 'created_at desc', per_page: @perpage
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @images }
    end
  end

  # GET /images/1
  # GET /images/1.json
  def show
    @image = Image.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/new
  # GET /images/new.json
  def new
    @image = Image.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /images
  # POST /images.json
  def create
  
    if params[:imgs]
      params[:imgs].each do |image|
         img = Image.find(image)
         /(.*)\.(jpg|png)/i.match(img.fname)
         iname = $1
         iformat = $2
         @path = "#{Rails.root}" #default upload path
         Dir.chdir(@path)                                   
         File.unlink("#{@path}/#{img.path}/originals/#{img.fname}")
         File.unlink("#{@path}/#{img.path}/image_thumb/#{iname}.#{iformat}")
         File.unlink("#{@path}/#{img.path}/75x75/#{iname}.#{iformat}")
         if File.exists?("#{@path}/#{img.path}/galery_thumb/#{iname}.png")
           File.unlink("#{@path}/images/galery_thumb/#{iname}.png")
         end
         img.destroy
      end
      respond_to do |format|
        format.html { redirect_to images_url, notice: 'Images deleted' }
        format.json { head :no_content }
      end      
    else  
      @image = Image.new(params[:image])

      respond_to do |format|
        if @image.save
          format.html { redirect_to @image, notice: 'Image was successfully created.' }
          format.json { render json: @image, status: :created, location: @image }
        else
          format.html { render action: "new" }
          format.json { render json: @image.errors, status: :unprocessable_entity }
        end
      end
      
    end
  end

  # PUT /images/1
  # PUT /images/1.json
  def update
    @image = Image.find(params[:id])    
    if @image.fname != params[:image]['fname']
      /(.*)\.(jpg|png)/i.match(@image.fname)
      iname = $1
      iformat = $2    
      paths = "originals", "75x75", "image_thumb"
      paths.each do |subdir|
        Dir.chdir("#{Rails.root}/#{@image.path}/#{subdir}")
        file1 = File.open(@image.fname, "r")          
        file2 = File.open(params[:image]['fname'], "w")
        file1.each {|line| file2.puts(line)}
        File.unlink(@image.fname)
      end

    end
    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to @image, notice: "Image was #{params[:image]['fname']} successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
#    @image = Image.find(image_id)
    @image = Image.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Images deleted' }
      format.json { head :no_content }
    end
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout "main"
  skip_before_filter :authorize
  def index
    @table_cells = Hash.new
    @cat_thumbs = Hash.new{|h,k| h[k]=Hash.new(&h.default_proc) }
    cthumb = ""
    @categories_number = Category.all.count
    @row_number = (((@categories_number/2).to_i)+1)
    
    Category.all.each do |ff|
      Gallery.where(:category_id => ff.id).each do |ss| 
        ct = Image.where(:gallery_id => ss.id, :gthumb => true).all(:limit => 1, :order => 'random()')
        ct.each do |cth|
          /(.*)\.jpg|png/i.match(cth.fname)
          iname = $1
          cthumb = "../#{cth.path}/category_thumb/#{iname}.png"
        end
      end
      while(1) do 
        key1 = rand(1..3)
        key2 = rand(1..@row_number)
        if @cat_thumbs[key1][key2] == {}
          @cat_thumbs[key1][key2] = "#{cthumb}:#{ff.id}"
          break
        end
      end

    end  

  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/cshow_helper.rb
module CshowHelper
end

app/helpers/dirlist_helper.rb
module DirlistHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/gshow_helper.rb
module GshowHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/ishow_helper.rb
module IshowHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <% img = "../../#{@image.path}/image_thumb/#{@image.fname}"%>
  <div class="field">
    <img src="<%= img %>" alt="<%= @image.fname %>" width="200" />
  </div>
  <div class="field">
    <%= f.label :fname %><br />
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :gallery %><br />
    <select id="image_gallery_id" name="image[gallery_id]">
      <% Gallery.all.each do |gallery| %>
        <% selected = 'selected="selected"' if @image.gallery_id == gallery.id %>
        <option value="<%= gallery.id %>" <%= selected %> ><%= gallery.title %></option>
      <% end %>
    </select>
  </div>
  <div class="field">
    <%= f.label :seentimes %><br />
    <%= f.number_field :seentimes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1 class="page_title">Editing image</h1>

<%= render 'form' %>

<div class="actions">
<%= link_to 'Back', images_path %>
</div>

app/views/images/index.html.erb
 <div class="page_title"><h1>Listing images</h1></div>

<%#= form_tag(:controller => 'images',:action=>'destroy', :method => "destroy") do %>
<%= form_tag(images_path, :method => "post") do %>
  <table class="main">
    <tr >
      <th></th>
      <th>Thumb</th>
      <th>Fname</th>
      <th>Gallery</th>
      <th>Category</th>      
      <th colspan="2"></th>
    </tr>
  <% ii = 0 %>
  <% @images.each do |image| %>
    <% ii += 1 %>
    <% ii%2 == 0 ? style = "class='odd'" : style = ' ' %>
    <% img = "../#{image.path}/75x75/#{image.fname}"%>
    <tr <%= style %>>
      <td class="tablecells"><input type=checkbox name=imgs[] value='<%= image.id %>'></td>
      <td><a href="/images/<%=image.id%>"><img src="<%= img %>" alt="<%= image.fname %>" width="75" height="75"/></a></td>
      <td><%= image.fname %></td>
      <td><%= image.gallery.title %></td>  <!-- same as Gallery.find(image.gallery_id).title -->
      <td><%= image.gallery.category.title %></td>
      <td><%= link_to 'Edit', edit_image_path(image) %></td>
    </tr>
  <% end %>
    <% perpage_params = "perpage=#{params[:perpage]}&" if params[:perpage]%>
    <tr>
      <td colspan="2"><%= submit_tag "Delete Images" %></td>
      <td colspan="2"><FORM NAME="galleries">
            <SELECT NAME="select" ONCHANGE="goto(this.form)" SIZE="1">
            <OPTION VALUE="">-------Choose Gallery-------
            <% Gallery.all.each do |gallery_row| %>
               <OPTION VALUE="/images?<%= perpage_params%>gal=<%=gallery_row.id%>"> <%=gallery_row.title%>
            <% end %>
          </FORM>
      </td>
      <% gallery_params = "gal=#{params[:gal]}&" if params[:gal]%>
      <td colspan="2">Show <a href="/images?<%=gallery_params%>perpage=10">10</a> | <a href="/images?<%=gallery_params%>perpage=20">20</a> | <a href="/images?<%=gallery_params%>perpage=50">50</a> | <a href="/images?<%=gallery_params%>perpage=100">100</a></td>
    </tr>
  </table>

<div class="actions"><%= will_paginate @images %></div>

<% end %>
<% if params[:imgs] %>
  <% params[:imgs].each do |ss| %>
    <%= ss %>
  <% end %>
<% end %>
<br />

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<div class="page_title"><h1>Image <%= @image.fname %></h1></div>
<% if (notice) %>
  <p id="notice"><%= notice %></p>
<% end %>
<div id="left">
	<p>
	  <b>Fname:</b>
	  <%= @image.fname %>
	</p>
	
	<p>
	  <b>Description:</b>
	  <%= @image.description %>
	</p>
	
	<p>
	  <b>Gallery:</b>
	  <%= @image.gallery.title %>
	</p>
	
	<p>
	  <b>Category:</b>
	  <%= @image.gallery.category.title %>
	</p>
	
	<p>
	  <b>Seentimes:</b>
	  <%= @image.seentimes %>
	</p>
</div>
<% img = "../#{@image.path}/originals/#{@image.fname}"%>
<div id="right">
	<img src="<%= img %>" alt="<%= @image.fname %>" width="800" />
</div>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>